// ======= DO NOT EDIT THIS FILE =============
//This stack is used for Graph depth-first traversal
//-----------------------------------------------------------------------

import java.util.*;

public class Stack {

    LinkedList<String> t;

    Stack() {
        t = new LinkedList<String>();
    }

    boolean isEmpty() {
        return (t.isEmpty());
    }

    void clear() {
        t.clear();
    }

    void push(String x) {
        t.addLast(x);
    }

    String pop() {
        if (isEmpty()) {
            return (null);
        }
        return (t.removeLast());
    }

    String top() {
        if (isEmpty()) {
            return (null);
        }
        return (t.getLast());
    }
}
